cpu:
  svd: STM32F427.svd
  vector_table: 0x08008000
  #id: 0x1234_5678_BABE_1234_5678_BABE
regions:
  - name: NULL_forgiveness
    start: 0x00000000
    size: 4096
  - name: ROM
    start: 0x08000000
    load: mono_6ks.bin
    size: 0x80000
  - name: RAM-CCM
    start: 0x10000000
    size: 0x18000
  - name: RAM
    start: 0x20000000
    size: 0x2ffff
framebuffers:
  - name: Touchscreen
    width: 480
    height: 320
    mode: rgb565
    sdl: true
  - name: LCD
    width: 5760
    height: 3600
    mode: gray8
    sdl: true
    downscale: 128
peripherals:
  software_spi:
    - name: SW_SPI_TOUCH
      cs: PD12
      clk: PD13
      mosi: PG4
      miso: PG3
devices:
  touchscreen:
    - peripheral: SW_SPI_TOUCH
      framebuffer: Touchscreen
      touch_detected_pin: PG6
      swap_x_y: true
      flip_x: true
      flip_y: true
  spi_flash:
    - peripheral: SPI1
      jedec_id: 0xef4016
      file: mono_6ks_flash.bin
      size: 0x1000000
  #usart_probe:
  #  - peripheral: UART4
  display:
    - peripheral: FMC.BANK1
      framebuffer: Touchscreen
      cmd_addr_bit: 0x10000
#      replies:
#        - cmd: 0xd3 # id4
#          data: [0x00, 0x00, 0x94, 0x88]
#        - cmd: 0xa1
#          data: [0x00, 0x93, 0x30, 0x93]
#        - cmd: 0x04 # device id
#          data: [0x30, 0x54, 0x80, 0x66]
  lcd:
    - peripheral: SPI3
      framebuffer: LCD
patches:
  # Generate these with ./asm.py
  # NOP systick delay
  - start: 0x08001a80
    data: [0x70, 0x47]
  - start: 0x08027750
    data: [0x70, 0x47]
  - start: 0x08017b80
    data: [0x70, 0x47]
  - start: 0x08051e98
    data: [0x70, 0x47]
  # NOP systick delay
  - start: 0x08051ee8
    data: [0x70, 0x47]    
# NOP display drawing
  - start: 0x0801d13c
    data: [0x70, 0x47]
# NOP Display reset pin 
  - start: 0x08000ec6
    data: [0x70, 0x47]
# Exit some compare loop
  - start: 0x0800fdfe
    data: [0x70, 0x47]  
  - start: 0x0800fe02
    data: [0x70, 0x47]  
  - start: 0x0800fe04
    data: [0x70, 0x47]
  - start: 0x0800fdf4
    data: [0x70, 0x47]
  - start: 0x08017bae
    data: [0x1, 0x21]
  - start: 0x08017b8a
    data: [0x1, 0x21]
  - start: 0x0800e6c8
    data: [0x1, 0x21]
  - start: 0x08016870
    data: [0x70, 0x47]
 # # NOP USB OTG? init
  - start: 0x08012530
    data: [0x70, 0x47]
 # # NOP ADC again
  - start: 0x08015ce0
    data: [0x70, 0x47]
 # # NOP ADC again
  - start: 0x08015d9e
    data: [0x70, 0x47]
 # # NOP ADC again
  - start: 0x08015cea
    data: [0x70, 0x47]
  - start: 0x08017234
    data: [0x70, 0x47]
#Nop USB HS
  - start: 0x08020f74
    data: [0x70, 0x47]
#Nop USB HS
  - start: 0x080125a0
    data: [0x70, 0x47]
# Return 1
  - start: 0x0800acde
    data: [0x1, 0x21]
  - start: 0x08015cac
    #data: [0x70, 0x47]
    data: [0x1, 0x21]
  - start: 0x0800acbc
    data: [0x70, 0x47]
  - start: 0x08026c00
    data: [0x70, 0x47]
